### ISSUE TITLE
梦境床睡觉不进入梦境

### ISSUE THREAD

**Issue by yb4188** [Alumopper/Dreamland#1]
win11,Fluent Launcher,.minecraft
版本：1.19.3-Forge-44.1.23
往床上仍梦之尘，梦境床晚上睡觉，不进入梦境，一个人俩人都不行
用命令获取梦境传送门就可以传送，不知道为啥，看日志也不报错

![image](https://github.com/Alumopper/Dreamland/assets/73260668/11e2a74d-4ec4-4f4b-878b-fa407c2c01e1)
![image](https://github.com/Alumopper/Dreamland/assets/73260668/37a384bc-68b8-4f58-875e-1cddb475126a)
![image](https://github.com/Alumopper/Dreamland/assets/73260668/14343279-e07b-46a7-89dd-28a8f67b1c11)

**Comment by yb4188** [comment]
用的是：Omega 1.0

**Comment by Alumopper** [comment]
很怪，不能复现这个bug
看起来服务端出现了巨大的延迟问题，不知道是不是数据包导致的，或者因为服务端tick延迟导致的数据包出现功能性问题

**Comment by yb4188** [comment]
![image](https://github.com/Alumopper/Dreamland/assets/73260668/cb5afa56-2274-4c61-ab77-32d36af429b7)

我又一个人试了一下，没开局域网就单机一个人
进游戏改生存模式，打僵尸爆梦之尘然后仍床上睡觉


日志：

[295月2023 16:10:12.450] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Dong, --version, 1.19.4-Forge-45.0.64, --gameDir, D:\wdsj\Minecraft 1.19.4\.minecraft\versions\1.19.4-Forge-45.0.64, --assetsDir, D:\wdsj\Minecraft 1.19.4\.minecraft\assets, --assetIndex, 3, --uuid, 2a5682c8768d5392400f7bc8b045573e, --accessToken, ????????????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, Mojang, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 45.0.64, --fml.mcVersion, 1.19.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230314.122934, --width, 854, --height, 480]
[295月2023 16:10:12.468] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.7 by Amazon.com Inc.; OS Windows 10 arch amd64 version 10.0
[295月2023 16:10:12.878] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/wdsj/Minecraft%201.19.4/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2391!/ Service=ModLauncher Env=CLIENT
[295月2023 16:10:13.272] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\wdsj\Minecraft 1.19.4\.minecraft\libraries\net\minecraftforge\fmlcore\1.19.4-45.0.64\fmlcore-1.19.4-45.0.64.jar is missing mods.toml file
[295月2023 16:10:13.357] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\wdsj\Minecraft 1.19.4\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19.4-45.0.64\javafmllanguage-1.19.4-45.0.64.jar is missing mods.toml file
[295月2023 16:10:13.418] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\wdsj\Minecraft 1.19.4\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19.4-45.0.64\lowcodelanguage-1.19.4-45.0.64.jar is missing mods.toml file
[295月2023 16:10:13.467] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\wdsj\Minecraft 1.19.4\.minecraft\libraries\net\minecraftforge\mclanguage\1.19.4-45.0.64\mclanguage-1.19.4-45.0.64.jar is missing mods.toml file
[295月2023 16:10:13.544] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[295月2023 16:10:15.309] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19.4-Forge-45.0.64, --gameDir, D:\wdsj\Minecraft 1.19.4\.minecraft\versions\1.19.4-Forge-45.0.64, --assetsDir, D:\wdsj\Minecraft 1.19.4\.minecraft\assets, --uuid, 2a5682c8768d5392400f7bc8b045573e, --username, Dong, --assetIndex, 3, --accessToken, ????????????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, Mojang, --versionType, release, --width, 854, --height, 480]
[295月2023 16:10:20.868] [Datafixer Bootstrap/INFO] [com.mojang.datafixers.DataFixerBuilder/]: 180 Datafixer optimizations took 112 milliseconds
[295月2023 16:10:22.587] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/D:/wdsj/Minecraft%201.19.4/.minecraft/libraries/net/minecraft/client/1.19.4-20230314.122934/client-1.19.4-20230314.122934-srg.jar%23152!/assets/.mcassetsroot' uses unexpected schema
[295月2023 16:10:22.588] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/D:/wdsj/Minecraft%201.19.4/.minecraft/libraries/net/minecraft/client/1.19.4-20230314.122934/client-1.19.4-20230314.122934-srg.jar%23152!/data/.mcassetsroot' uses unexpected schema
[295月2023 16:10:22.629] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[295月2023 16:10:24.193] [Render thread/ERROR] [net.minecraft.client.Minecraft/]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.18.38.jar%23101!/:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-3.18.38.jar%23101!/:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.18.38.jar%23101!/:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.18.38.jar%23101!/:?]
	at net.minecraft.client.Minecraft.m_193585_(Minecraft.java:650) ~[client-1.19.4-20230314.122934-srg.jar%23152!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:411) ~[client-1.19.4-20230314.122934-srg.jar%23152!/:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[1.19.4.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.0.64.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.18.38.jar%23101!/:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.18.38.jar%23101!/:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.18.38.jar%23101!/:?]
	... 18 more
[295月2023 16:10:24.195] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Dong
[295月2023 16:10:24.301] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.3.1 build 7
[295月2023 16:10:24.870] [modloading-worker-0/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 45.0.64, for MC 1.19.4 with MCP 20230314.122934
[295月2023 16:10:24.870] [modloading-worker-0/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v45.0.64 Initialized
[295月2023 16:10:26.091] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[295月2023 16:10:26.122] [Render thread/INFO] [net.minecraft.server.packs.resources.ReloadableResourceManager/]: Reloading ResourceManager: vanilla, mod_resources, file/Dreamland
[295月2023 16:10:26.426] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[295月2023 16:10:26.661] [Worker-Main-12/WARN] [net.minecraft.client.renderer.texture.SpriteLoader/]: Texture dreamland:item/picture/system_loading5 with size 1500x1000 limits mip level from 4 to 2
[295月2023 16:10:26.661] [Worker-Main-12/WARN] [net.minecraft.client.renderer.texture.SpriteLoader/]: Texture dreamland:item/fishing_rod_blueprint with size 210x210 limits mip level from 2 to 1
[295月2023 16:10:26.661] [Worker-Main-12/WARN] [net.minecraft.client.renderer.texture.SpriteLoader/]: Texture dreamland:item/nightmare_essence with size 225x225 limits mip level from 1 to 0
[295月2023 16:10:27.882] [Worker-Main-17/WARN] [net.minecraft.client.resources.model.ModelManager/]: Missing textures in model minecraft:light_blue_dye#inventory:
    minecraft:textures/atlas/blocks.png:dreamland:blank
[295月2023 16:10:27.922] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: BETA Current: 45.0.64 Target: 45.0.64
[295月2023 16:10:29.334] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/]: Missing sound for event: minecraft:item.goat_horn.play
[295月2023 16:10:29.337] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[295月2023 16:10:29.340] [Render thread/WARN] [net.minecraft.client.sounds.SoundEngine/]: Missing sound for event: minecraft:music.overworld.cherry_grove
[295月2023 16:10:29.634] [Render thread/INFO] [com.mojang.blaze3d.audio.Library/]: OpenAL initialized on device OpenAL Soft on 扬声器 (Realtek(R) Audio)
[295月2023 16:10:29.635] [Render thread/INFO] [net.minecraft.client.sounds.SoundEngine/SOUNDS]: Sound engine started
[295月2023 16:10:29.667] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 8192x8192x4 minecraft:textures/atlas/blocks.png-atlas
[295月2023 16:10:29.805] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[295月2023 16:10:29.805] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[295月2023 16:10:29.806] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[295月2023 16:10:29.806] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[295月2023 16:10:29.808] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 64x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[295月2023 16:10:29.809] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[295月2023 16:10:29.810] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[295月2023 16:10:29.810] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[295月2023 16:10:30.107] [Render thread/WARN] [net.minecraft.client.renderer.ShaderInstance/]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[295月2023 16:10:30.161] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[295月2023 16:10:30.163] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[295月2023 16:10:30.163] [Render thread/INFO] [net.minecraft.client.renderer.texture.TextureAtlas/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[295月2023 16:10:31.225] [Realms Notification Availability checker #1/INFO] [com.mojang.realmsclient.client.RealmsClient/]: Could not authorize you against Realms server: Invalid session id
[295月2023 16:10:50.021] [Render thread/INFO] [net.minecraft.server.packs.repository.FolderRepositorySource/]: Found non-pack entry 'D:\wdsj\Minecraft 1.19.4\.minecraft\versions\1.19.4-Forge-45.0.64\saves\梦境\datapacks\LICENSE', ignoring
[295月2023 16:10:50.021] [Render thread/INFO] [net.minecraft.server.packs.repository.FolderRepositorySource/]: Found non-pack entry 'D:\wdsj\Minecraft 1.19.4\.minecraft\versions\1.19.4-Forge-45.0.64\saves\梦境\datapacks\README.md', ignoring
[295月2023 16:10:50.025] [Render thread/INFO] [net.minecraft.server.packs.repository.FolderRepositorySource/]: Found non-pack entry 'D:\wdsj\Minecraft 1.19.4\.minecraft\versions\1.19.4-Forge-45.0.64\saves\梦境\datapacks\TODO', ignoring
[295月2023 16:10:51.130] [Worker-Main-8/ERROR] [net.minecraft.Util/]: Invalid path in pack: dream:functions/memory_story/final_boss1/skills/X_X/load.mcfunction, ignoring
[295月2023 16:10:51.134] [Worker-Main-8/ERROR] [net.minecraft.Util/]: Invalid path in pack: dream:functions/memory_story/final_boss1/skills/X_X/tick.mcfunction, ignoring
[295月2023 16:10:51.134] [Worker-Main-8/ERROR] [net.minecraft.Util/]: Invalid path in pack: dream:functions/memory_story/final_boss1/技能列表.txt, ignoring
[295月2023 16:10:51.142] [Worker-Main-8/ERROR] [net.minecraft.Util/]: Invalid path in pack: dream:functions/memory_story/final_boss2/技能列表.txt, ignoring
[295月2023 16:10:51.143] [Worker-Main-19/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [minecart:spider (from file/Dreamland)] as it is missing following references: minecart:spider (from file/Dreamland)
[295月2023 16:10:52.516] [Render thread/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Loaded 7 recipes
[295月2023 16:10:52.917] [Render thread/ERROR] [net.minecraft.server.ServerAdvancementManager/]: Parsing error loading custom advancement dream:func/natrual_crystal: Unknown required criterion 'dreamland:mountains'
[295月2023 16:10:52.953] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 1222 advancements
[295月2023 16:10:53.313] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Starting integrated minecraft server version 1.19.4
[295月2023 16:10:53.314] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Generating keypair
[295月2023 16:10:54.385] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Preparing start region for dimension minecraft:overworld
[295月2023 16:10:56.858] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: 准备生成区域中：0%
[295月2023 16:10:57.014] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: 准备生成区域中：0%
[295月2023 16:10:57.014] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: 准备生成区域中：0%
[295月2023 16:10:57.015] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: 准备生成区域中：0%
[295月2023 16:10:57.054] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: 准备生成区域中：0%
[295月2023 16:10:57.054] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: 准备生成区域中：0%
[295月2023 16:10:57.407] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: 准备生成区域中：0%
[295月2023 16:10:57.925] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: 准备生成区域中：0%
[295月2023 16:10:58.429] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: 准备生成区域中：0%
[295月2023 16:10:58.918] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: 准备生成区域中：26%
[295月2023 16:10:59.420] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: 准备生成区域中：91%
[295月2023 16:10:59.445] [Server thread/INFO] [net.minecraftforge.server.permission.PermissionAPI/]: Successfully initialized permission handler forge:default_handler
[295月2023 16:10:59.451] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Time elapsed: 5054 ms
[295月2023 16:11:00.026] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Changing view distance to 12, from 10
[295月2023 16:11:00.030] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Changing simulation distance to 12, from 0
[295月2023 16:11:00.354] [Render thread/WARN] [io.netty.util.internal.SystemPropertyUtil/]: Unable to parse the boolean system property 'java.net.preferIPv6Addresses':system - using the default value: false
[295月2023 16:11:01.021] [Netty Local Client IO #0/INFO] [net.minecraftforge.network.NetworkHooks/]: Connected to a modded server.
[295月2023 16:11:01.154] [Server thread/INFO] [net.minecraft.server.players.PlayerList/]: Dong[local:E:c56ad2b3] logged in with entity id 80 at (-536.3261030585409, 130.99313556517845, -120.82370358964866)
[295月2023 16:11:01.261] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Dong加入了游戏
[295月2023 16:11:01.594] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 248 advancements
[295月2023 16:11:22.335] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: [Dong: 已将自己的游戏模式设置为生存模式]
[295月2023 16:11:22.339] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] 已将自己的游戏模式设置为生存模式
[295月2023 16:11:25.298] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Saving and pausing game...
[295月2023 16:11:25.317] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/minecraft:overworld
[295月2023 16:11:25.345] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:chaos
[295月2023 16:11:25.346] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:nightmare
[295月2023 16:11:25.348] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:memory_abyss
[295月2023 16:11:25.349] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:the_edge_of_dream
[295月2023 16:11:25.350] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:the_end_of_dream
[295月2023 16:11:25.350] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:sweetdream
[295月2023 16:11:25.351] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/minecraft:the_end
[295月2023 16:11:25.352] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/btoe:space
[295月2023 16:11:25.352] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/minecraft:the_nether
[295月2023 16:12:00.415] [Render thread/INFO] [net.minecraft.advancements.AdvancementList/]: Loaded 248 advancements
[295月2023 16:12:58.413] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] 已设置重生点
[295月2023 16:13:12.546] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Saving and pausing game...
[295月2023 16:13:12.554] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/minecraft:overworld
[295月2023 16:13:12.560] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:chaos
[295月2023 16:13:12.561] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:nightmare
[295月2023 16:13:12.562] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:memory_abyss
[295月2023 16:13:12.562] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:the_edge_of_dream
[295月2023 16:13:12.563] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:the_end_of_dream
[295月2023 16:13:12.564] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:sweetdream
[295月2023 16:13:12.564] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/minecraft:the_end
[295月2023 16:13:12.565] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/btoe:space
[295月2023 16:13:12.565] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/minecraft:the_nether
[295月2023 16:15:03.959] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Dong lost connection: 连接中断
[295月2023 16:15:03.959] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Dong退出了游戏
[295月2023 16:15:03.969] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Stopping singleplayer server as player logged out
[295月2023 16:15:04.013] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[295月2023 16:15:04.013] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[295月2023 16:15:04.013] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[295月2023 16:15:05.559] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/minecraft:overworld
[295月2023 16:15:05.665] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:chaos
[295月2023 16:15:05.686] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:nightmare
[295月2023 16:15:05.687] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:memory_abyss
[295月2023 16:15:05.688] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:the_edge_of_dream
[295月2023 16:15:05.688] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:the_end_of_dream
[295月2023 16:15:05.689] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/dream:sweetdream
[295月2023 16:15:05.693] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/minecraft:the_end
[295月2023 16:15:05.693] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/btoe:space
[295月2023 16:15:05.694] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[梦境]'/minecraft:the_nether
[295月2023 16:15:05.710] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (梦境): All chunks are saved
[295月2023 16:15:05.710] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (chaos): All chunks are saved
[295月2023 16:15:05.710] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (nightmare): All chunks are saved
[295月2023 16:15:05.710] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (memory_abyss): All chunks are saved
[295月2023 16:15:05.710] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (the_edge_of_dream): All chunks are saved
[295月2023 16:15:05.710] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (the_end_of_dream): All chunks are saved
[295月2023 16:15:05.710] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (sweetdream): All chunks are saved
[295月2023 16:15:05.710] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[295月2023 16:15:05.710] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (space): All chunks are saved
[295月2023 16:15:05.710] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[295月2023 16:15:05.710] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[295月2023 16:15:08.466] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!

**Comment by yb4188** [comment]
补充一下，这俩版本我都有测试都是睡觉不做梦，这俩版本就装了一个mod就是自定义联机
![image](https://github.com/Alumopper/Dreamland/assets/73260668/ae0acf99-c6f0-4ba9-86fa-012d268e470b)

**Comment by yb4188** [comment]
![image](https://github.com/Alumopper/Dreamland/assets/73260668/ed8b0ef7-f5ff-4851-baf6-b70bb5e71d36)
成功了，我换回了纯净版就好了
![image](https://github.com/Alumopper/Dreamland/assets/73260668/2d101ebf-8dbf-4a4c-9fb0-0783b718652d)
是不是就是这一种可能，我使用的lanserverproperties-1.10-forge.jar，这个自定义联机插件导致的

**Comment by Alumopper** [comment]
以前还没在forge端中测试过，不知道forge会导致什么影响。
因为数据包本身基于原版，如果mod修改了原版特性，很有可能就会导致奇怪的问题
晚上咱仔细排查一下

目前知道的是forge会影响nbt，但是是否对核心功能有影响也不知道

**Comment by yb4188** [comment]
我已经确定了，跟插件毫无关系，但是跟forge有关系，用forge这个版本就炸，别管是1.19.3还是1.19.2

**Comment by Alumopper** [comment]
咱回去看看

**Comment by yb4188** [comment]
说错了是1.19.4和1.19.3

**Comment by yb4188** [comment]
顺便问一下，剧情咋触发的，进入梦境了已经，没发现剧情

**Comment by Alumopper** [comment]
还没完善wiki，光顾着开发了，很多合成表都没写出来
可能要等一段时间了，我会尽快补充wiki

**Comment by Alumopper** [comment]
应该不是forge的问题。
```mcfunction
#记录每个玩家进入两个梦境的概率
scoreboard objectives add dream_likelihood dummy "玩家进入两个梦境的概率"
execute as @a unless score @s dream_likelihood matches 0..100 run scoreboard players set @s dream_likelihood 50
```
这段命令用于初始化进入梦境的概率。但是由于世界刚刚加载的第一个tick并没有任何玩家在世界中，因此这个命令不能正常初始化玩家进入梦境世界的概率
会在本周末的快照中修复。目前的解决办法是，**在游戏中输入/reload重载即可，或者手动执行上面的两行命令**。
